name = "ParseUnparse"
uuid = "caaa8bb7-a042-43a4-a1c9-7594415e1478"
authors = ["Neven Sajko <s@purelymail.com> and contributors"]
version = "1.0.0-DEV"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"

[compat]
AbstractTrees = "0.4"
julia = "1.9"
